COURSE_ACTS(COURSE_BOB, _(" 1 WINDSWEPT VALLEY"),
       _("BIG BULLY ON THE SUMMIT")     , _("KARTRACE WITH MAGIKOOPA THE QUICK") , _("SHOOT THE CLOWN IN THE SKY"),
       _("FIND THE 8 RED COINS")          , _("GRAND DAD WINGS TO THE SKY")        , _("BEHIND CHAMP CHOMP'S GATE"))

COURSE_ACTS(COURSE_WF, _(" 2 FROSTBITE FORTRESS"),
       _("CHIP OFF TREEP'S BARK")        , _("TO THE TOP OF THE FORTRESS")    , _("SHOOT INTO THE SKY"),
       _("RED COINS ON THE FLOATING ISLE"), _("FALL ONTO THE CAGED ICEBERG")    , _("BLAST AWAY THE VERY TALL WALL"))

COURSE_ACTS(COURSE_JRB, _(" 3 SALTY SALTY SEA"),
       _("YE BURIED TREASURE FOR ME!")    , _("CAN THE SHARK COME OUT TO PLAY?") , _("JEWELS OF THE OCEAN CAVE"),
       _("RED COINS ON THE SHIP AFLOAT")  , _("BLAST TO THE ICE")     , _("THROUGH THE TWICH STREAM"))

COURSE_ACTS(COURSE_CCM, _(" 4 COLD, COLD CREVASSE"),
       _("SECRET SLIDE THROWN AWAY")             , _("LI'L PENGUIN LOST AND FOUND")             , _("BIG HUMAN RACE"),
       _("FROSTY SLIDE FOR 8 RED COINS")  , _("SNOWMAN'S DEAD")       , _("WALL KICKS WONT WORK"))

COURSE_ACTS(COURSE_BBH, _(" 5 PARANORMAL PARK"),
       _("GO ON A GHOST HUNT")            , _("RIDE BIG BOO'S MERRY-GO-ROUND") , _("SECRET OF THE HAUNTED BOOKS"),
       _("SEEK THE 8 RED COINS")          , _("BIG BOO'S BALCONY")             , _("EYE TO EYE IN THE SECRET ROOM"))

COURSE_ACTS(COURSE_HMC, _(" 6 MAZE CAVE"),
       _("SWIMMING BOSS IN THE CAVERN")  , _("ELEVATE FOR 8 RED COINS")       , _("METAL-HEAD MARIO CAN MOVE SLOW!"),
       _("NAVIGATING THE MAZE")     , _("A-MAZE-ING EXIT")     , _("WATCH FOR FALLING ROCKS"))

COURSE_ACTS(COURSE_LLL, _(" 7 NOT-SO-LETHAL LAVA LAND"),
       _("BOIL THE BIG BEANS")            , _("BULLY THE BOB-OMBS")             , _("8-COIN PUZZLE WITH 15 PIECES"),
       _("RED LOG ROLLING")           , _("HOT-FOOT-IT INTO THE LAVA")  , _("TOUR IN THE LAVA"))

COURSE_ACTS(COURSE_SSL, _(" 8 QUICKSAND LAND"),
       _("IN THE TALONS OF THE BIG BAD") , _("SHINING ATOP THE UFO")      , _("INSIDE THE ANCIENT UFO"),
       _("STAND TALL ON THE FOUR ELEMENTAL TOWERS"), _("FREE FLYING FOR 8 RED COINS")   , _("UFO PUZZLE"))

COURSE_ACTS(COURSE_DDD, _(" 9 SIRE, SIRE DOCKS"),
       _("BOARD WART'S SUB")            , _("CHESTS IN THE PAST")         , _("POLE-JUMPING FOR RED COINS"),
       _("THROUGH THE TWICH STREAM (re)")        , _("THE MANTA RAY'S REWIND")        , _("COLLECT THE ALL CAPS..."))

COURSE_ACTS(COURSE_SL, _("10 SNOW MOUNTAIN SUMMIT"),
       _("SNOWMAN'S ON LIFE SUPPORT")            , _("CHILL WITH THE DS BULLY")          , _("IN THE ICE AGE"),
       _("POLYWHIRL FROM THE POND")  , _("SHELL SHREDDIN' FOR RED COINS") , _("INTO THE ICE"))

COURSE_ACTS(COURSE_WDW, _("11 ICEBERG IMAGE"),
       _("SHOCKING ICEBERG IMAGES!")         , _("TOP O' THE ICEBERG")               , _("SECRETS IN THE ICEBERG & SKY"),
       _("EXPRESS ICEBERG--HURRY UP!")   , _("GO TO ICEBERG FOR RED COINS")      , _("QUICK RACE THROUGH ICEBERG!"))

COURSE_ACTS(COURSE_TTM, _("12 SMALL, SMALL MOUNTAIN"),
       _("DRAGON SCALE THE MOUNTAIN")            , _("MYSTERY OF THE PUPPET CAGE")    , _("SCARY 'SHROOMS, RED COINS"),
       _("MYSTERIOUS MOUNTAINS")       , _("BREATHTAKING VIEW FROM THE EDGE") , _("BLAST TO THE 1-UP MUSHROOM"))

COURSE_ACTS(COURSE_THI, _("13 A-Z ISLAND"),
       _("PLUCK THE PIRANHA PLANT")      , _("THE TIP TOP OF THE Z ISLAND"), _("REMATCH WITH MAGIKOOPA THE QUICK"),
       _("FIVE 8-BIT SECRETS")       , _("WIGGLER'S RED COINS")           , _("MAKE CATERPILLOW SQUIRM"))

COURSE_ACTS(COURSE_TTC, _("14 TICK TOCK MOCK"),
       _("ROLL INTO THE MAGE")            , _("THE PIT AND THE GRAND BALL-N-CHAIN")     , _("GET A HAND OR TWO"),
       _("STOMP ON THE MOP")           , _("TIMED JUMPS ON BLINKING BARS")    , _("STOP TIME FOR RED COINS"))

COURSE_ACTS(COURSE_RR, _("15 RAINBOW BIDE"),
       _("CRUISER CROSSING THE OXBOW")  , _("THE WHITE HOUSE IN THE SKY")      , _("COINS AMASSED IN A MAZE"),
       _("SINGIN' IN THE BREEZE")        , _("TRICKY CUBES!")             , _("SOMEWHERE OVER THE OXBOW"))

SECRET_STAR(COURSE_BITDW, _("   WART IN THE NIGHTMARE WORLD"))
SECRET_STAR(COURSE_BITFS, _("   WART IN THE WATER SEA"))
SECRET_STAR(COURSE_BITS, _("   WART IN SPACE"))
SECRET_STAR(COURSE_PSS, _("   THE PRINCESS'S NOT-SO-SECRET SLIDE"))
SECRET_STAR(COURSE_COTMC, _("   CAVERN OF THE METAL CAP"))
SECRET_STAR(COURSE_TOTWC, _("   TOWER OF THE WING CAP"))
SECRET_STAR(COURSE_VCUTM, _("   VANISH CAP UNDER THE MOAT"))
SECRET_STAR(COURSE_WMOTR, _("   WING MARIO OVER THE OXBOW"))
SECRET_STAR(COURSE_SA, _("   THE SEACRET SEA"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("   CASTLE SECRET STARS"))

EXTRA_TEXT(0, _("ONE OF THE CASTLE'S SECRET STARS!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
